### ISSUE TITLE
Bug: Collapse functionality on cards

### ISSUE THREAD

**Issue by Anka-S** [Morgana-S/magic-december#19]
If you don't click the "Read more" button again, the content won't collapse. When you click on this card again, you will see the full information, not only the description.

**Comment by Morgana-S** [comment]
I would make the argument that this is a feature rather than a bug - if you accidentally click off the card and then click it again, you don't want to have to select the read more section again. It also only affects that card, so you still have to click read more on the other modals; shall we leave this as it is?

**Comment by Morgana-S** [comment]
Discussed with team on slack - will consider this a feature rather than a bug.
